=== terryf82/boston-crash-modeling/standards/concerns-schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "title": "Concerns",
    "description": "Defines the structure of a set of concerns",
    "type": "array",
    "items": {
        "title": "Concern",
        "description": "Defines the structure of a concern",
        "type": "object",
        "properties": {
            "id": {
                "description": "Unique identifier of concern",
                "type": ["string", "number"]
            },
            "source": {
                "description": "Source of concern",
                "type": "string",
                "enum": ["seeclickfix", "visionzero"]
            },
            "dateCreated": {
                "description": "Date concern was created, ISO8601 formatted",
                "type": "string",
                "format": "date-time"
            },
            "dateResolved": {
                "description": "Date concern was resolved, ISO8601 formatted",
                "format": "date-time"
            },
            "status": {
                "description": "Status of concern",
                "type": "string"
            },
            "category": {
                "description": "Primary category of concern",
                "type": "string"
            },
            "subCategories": {
                "description": "Subcategories of concern",
                "type": "array",
                "items": {
                    "type": "string"
                },
                "uniqueItems": true
            },
            "location": {
                "description": "Coordinates of concern, WGS84 formatted",
                "type": "object",
                "properties": {
                    "latitude": {
                        "description": "Latitude of concern",
                        "type": "number"
                    },
                    "longitude": {
                        "description": "Longitude of concern",
                        "type": "number"
                    }
                }
            },
            "address": {
                "description": "Address of concern",
                "type": "string"
            },
            "summary": {
                "description": "Summary of concern",
                "type": "string"
            }
        },
        "required": ["id", "source", "dateCreated", "status", "category", "location", "summary"]
    }
}

=== terryf82/boston-crash-modeling/standards/concerns-instance.json
[
    {
        "id": 14808,
        "source": "visionzero",
        "dateCreated": "2016-01-19T14:48:45.000Z",
        "status": "Unassigned",
        "category": "of something that is not listed here",
        "location": {
            "latitude": 42.354167552594284,
            "longitude": -71.05414378860903
        },
        "summary": "This intersection is dangerous. Cars don't follow the lane markings (ie go straight while in turn lane) so it's nearly impossible to safely position yourself on a bike. In a car, people are trying to move over/it's unclear where people are going."
    },
    {
        "id": 14809,
        "source": "visionzero",
        "dateCreated": "2016-01-19T14:57:03.000Z",
        "status": "Unassigned",
        "category": "people don't yield while going straight",
        "location": {
            "latitude": 42.33938397670106,
            "longitude": -71.0994798889095
        },
        "summary": "It's terrifying to walk over here. It seems like it's impossible to get the cars to stop stop, even at the crosswalks."
    },
    {
        "id": 14810,
        "source": "visionzero",
        "dateCreated": "2016-01-19T15:36:25.000Z",
        "status": "Unassigned",
        "category": "itâ€™s hard to see / low visibility",
        "location": {
            "latitude": 42.349364649630935,
            "longitude": -71.06656509857143
        },
        "summary": "cars coming around the corner of this wide one street are speeding and not visible for persons on the crosswalk"
    }
]
