=== terryf82/boston-crash-modeling/standards/crashes-schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "title": "Crashes",
    "description": "Defines the structure of a set of crashes",
    "type": "array",
    "items": {
        "title": "Crash",
        "description": "Defines the structure of a crash",
        "type": "object",
        "properties": {
            "id": {
                "description": "Unique identifier of crash",
                "type": ["string", "number"]
            },
            "dateOccurred": {
                "description": "Date crash occurred, ISO8601 formatted",
                "type": "string",
                "format": "date-time"
            },
            "location": {
                "description": "Coordinates of crash, WGS84 formatted",
                "type": "object",
                "properties": {
                    "latitude": {
                        "description": "Latitude of crash",
                        "type": "number"
                    },
                    "longitude": {
                        "description": "Longitude of crash",
                        "type": "number"
                    }
                }
            },
            "vehicles": {
                "description": "Vehicles involved in crash",
                "type": "array",
                "items": {
                    "title": "Vehicle",
                    "description": "Defines the structure of a vehicle",
                    "type": "object",
                    "properties": {
                        "category": {
                            "description": "Category of vehicle",
                            "type": "string",
                            "enum": ["car", "bike", "taxi", "bus", "truck"]
                        },
                        "quantity": {
                            "description": "Quantity of vehicles of this category",
                            "type": "number"
                        }
                    },
                    "required": ["category"]
                },
                "uniqueItems": true
            },
            "persons": {
                "description": "Persons involved in crash",
                "type": "array",
                "items": {
                    "title": "Person",
                    "description": "Defines the structure of a person",
                    "type": "object",
                    "properties": {
                        "category": {
                            "description": "Category of person",
                            "type": "string",
                            "enum": ["driver", "pedestrian", "cyclist", "other"]
                        },
                        "quantity": {
                            "description": "Quantity of persons",
                            "type": "number"
                        },
                        "injuryType": {
                            "description": "Type of injury",
                            "type": "string",
                            "enum": ["minor", "major", "fatal", "unknown"]
                        }
                    },
                    "required": ["category"]
                },
                "uniqueItems": true
            },
            "address": {
                "description": "Address of crash",
                "type": "string"
            },
            "summary": {
                "description": "Summary of crash",
                "type": "string"
            }
        },
        "required": ["id", "dateOccurred", "location"]
    }
}

=== terryf82/boston-crash-modeling/src/data/tests/data/osm_crash_file.json
[
    {
        "id": 1403832,
        "dateOccurred": "2016-01-01T00:56:45-05:00",
        "location": {
            "latitude": 42.3311855,
            "longitude": -71.0748389
        },
        "vehicles": [
            {
                "category": "car"
            }
        ],
        "summary": "REPORTED INJURIES   (P) (E) (F)"
    },
    {
        "id": 1403832,
        "dateOccurred": "2016-01-01T00:56:45-05:00",
        "location": {
            "latitude": 42.3611498,
            "longitude": -71.0645559
        },
        "vehicles": [
            {
                "category": "car"
            }
        ],
        "summary": "REPORTED INJURIES   (P) (E) (F)"
    },
    {
        "id": 1403832,
        "dateOccurred": "2016-01-01T00:56:45-05:00",
        "location": {
            "latitude": 42.333375,
            "longitude": -71.07736
        },
        "vehicles": [
            {
                "category": "car"
            }
        ],
        "summary": "REPORTED INJURIES   (P) (E) (F)"
    }

]

=== terryf82/boston-crash-modeling/src/data/tests/data/standardized/crashes.json
[
    {
        "id": 1403832,
        "dateOccurred": "2016-01-01T00:56:45-05:00",
        "vehicles": [
            { "category": "car" }
        ],
        "location": {
            "latitude": 42.236942,
            "longitude": -71.130909
        },
        "address": "14 Corona Street",
        "summary": "REPORTED INJURIES (P) (E) (F)"
    }
]
