=== terryf82/boston-crash-modeling/standards/points-schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "title": "Concerns",
    "description": "Defines the structure of a set of point-based features",
    "type": "array",
    "items": {
        "title": "Point Feature",
        "description": "Defines the structure of a point-based feature",
        "type": "object",
        "properties": {
            "feature": {
                "description": "Type of feature, e.g. traffic tickets",
                "type": "string"
            },
            "date": {
                "description": "Date for feature, ISO8601 formatted",
                "type": "string",
                "format": "date-time"
            },
            "category": {
                "description": "Category of entry",
                "type": "string"
            },
            "notes": {
                "description": "Notes for entry",
                "type": "string"
            },
            "location": {
                "description": "Coordinates of concern, WGS84 formatted",
                "type": "object",
                "properties": {
                    "latitude": {
                        "description": "Latitude of entry",
                        "type": "number"
                    },
                    "longitude": {
                        "description": "Longitude of entry",
                        "type": "number"
                    }
                }
            }
        },
        "required": ["feature", "location"]
    }
}

=== terryf82/boston-crash-modeling/src/data/tests/data/test_create_segments/additional_points.json
[{"feature": "parking_tickets", "date": "2016-05-17T00:00:00Z", "location": {"latitude": 42.38404209999999, "longitude": -71.1370766}, "category": "NO PARKING"}, {"feature": "parking_tickets", "date": "2014-01-04T15:50:00Z", "location": {"latitude": 42.38404209999999, "longitude": -71.1370766}, "category": "METER EXPIRED"}]
